name: Publish to Nuget

on: workflow_dispatch 

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      
      - name: nuget publish
        env:
            nuget_push: ${{ secrets.NUGET_API_KEY }}
        run: dotnet fsi build.fsx publish
